API_HOST_URL: 'https://classroom.blend-ed.com'
ENVIRONMENT_DISPLAY_NAME: 'blend-ED'
PLATFORM_NAME: 'blend-ED'
PLATFORM_DESTINATION_NAME: 'www.classroom.blend-ed.com'
FEEDBACK_EMAIL_ADDRESS: 'contact@blend-ed.com'
COURSE_SHARING_ENABLED : true
DISCUSSIONS_ENABLED : true
PUSH_NOTIFICATIONS : true
USER_PROFILES_ENABLED : true
VIDEO_TRANSCRIPT_ENABLED: true
DOWNLOAD_TO_SD_CARD_ENABLED: true
COURSE_DATES_ENABLED: true
TAB_LAYOUTS_ENABLED: true
ANNOUNCEMENTS_ENABLED: true
WHATS_NEW_ENABLED: false
COURSE_VIDEOS_ENABLED: false
YOUTUBE_PLAYER:
  ENABLED: true
  API_KEY: 'AIzaSyC0QvxzB6h5zh1oo3m1Gt4b7u6dX1PPmxuA'
DISCOVERY :
  COURSE:
    TYPE : 'webview'
    WEBVIEW : 
      SUBJECT_FILTER_ENABLED: true
      BASE_URL: 'https://blend-ed.com/org/'
      SEARCH_ENABLED: false
NEW_LOGISTRATION_ENABLED : true
CERTIFICATES_ENABLED : true

